Blocks:
  - STONE
  - COBBLESTONE
  - COBBLESTONE_STAIRS
  - COBBLE_WALL
  - MOSSY_COBBLESTONE
  - STEP
  - DOUBLE_STEP
  - BRICK
  - BRICK_STAIRS
  - SMOOTH_BRICK
  - SMOOTH_STAIRS
  - SANDSTONE
  - SANDSTONE_STAIRS
  - STAINED_CLAY
  - HARD_CLAY
  - COAL_ORE
  - COAL_BLOCK
  - IRON_ORE
  - IRON_BLOCK
  - GOLD_ORE
  - GOLD_BLOCK
  - REDSTONE_ORE
  - GLOWING_REDSTONE_ORE
  - REDSTONE_BLOCK
  - LAPIS_ORE
  - LAPIS_BLOCK
  - EMERALD_ORE
  - EMERALD_BLOCK
  - DIAMOND_ORE
  - DIAMOND_BLOCK
  - NETHERRACK
  - NETHER_BRICK
  - NETHER_BRICK_STAIRS
  - QUARTZ_ORE
  - QUARTZ_BLOCK
  - QUARTZ_STAIRS
  - GLOWSTONE
  - ENDER_STONE
  - GRASS
  - DIRT
  - SAND
  - GRAVEL
  - CLAY
  - SNOW
  - SNOW_BLOCK
  - SOUL_SAND
  - MYCEL